services:
  gitnote:
    image: gitnote:v1
    container_name: gitnote-api
    build:
      context: "./gitnote"
      dockerfile: "Dockerfile"
    ports:
      - "4000:3000"
    env_file: .env
    depends_on:
      - gitnote-sshd
    volumes:
      - ./git-repo:/git-repo  # 容器内用 ln 链接到对应目录
    logging:
      driver: json-file
      options:
        max-size: "5m"       # 单个日志文件最大 5MB
        max-file: "3"         # 最多保留 3 个日志文件（总计最多 15MB）


  gitnote-sshd:
    image: gitnote-sshd:v1
    container_name: gitnote-sshd
    build:
      context: "./sshd"
      dockerfile: "Dockerfile"
    ports:
      - "2222:22" # 替换为你指定的端口
    env_file: .env
    volumes:
      - ./git-repo/:/git-repo  # 容器内用 ln 链接到对应目录
      - ./sshd/ssh_keys:/ssh_keys


  gitnote-db:
    image: postgres:14.12
    container_name: gitnote-db
    volumes:
      - gitnote-db:/var/lib/postgresql/data  # 数据持久化
    env_file: .env
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "5m"       # 单个日志文件最大 5MB
        max-file: "3"         # 最多保留 3 个日志文件（总计最多 15MB）

volumes:
  gitnote-db:
